### ISSUE TITLE
Article about the app

### ISSUE THREAD

**Issue by infoekcz** [n000tavailable/tunedetective#1]
Hey,
I've tested your new app and I really like it.  I just ran into an error when searching for the artist Marilyn Manson. The app finds an old album and passes it off as the latest. ;)
Will the app also be available in the F-Droid store?
I wrote an article about the app on my tech site: https://infoek.cz/tunedetective-opensource-aplikace-2023/

Thanks for your work!

**Comment by n000tavailable** [comment]
Hey, thanks for nice words and for the article :)
About f-droid. I have to take a look since it is more complicated than other repos. at least that seems to be the case.

About your issue, to be honest i don't know what the problem might be. It could be a problem of the deezer api, which i have no influence on, or it could be that there are problems with older albums.

Old albums that were released earlier are still marked as new because they were resubmitted and have a "wrong" release date.

**Comment by noodlejetski** [comment]
it looks like it's already available on the IzzyOnDroid repo (:

https://apt.izzysoft.de/fdroid/index/apk/com.n0tavailable.tunedetective
